version: latest

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_USER: "BloodBank"
      POSTGRES_PASSWORD: "BloodBankDb2024!"
    container_name: bloodbank
    restart: always
    ports:
      - "15432:5432"
    networks:
      - postgres-compose-network
networks:
  postgres-compose-network:
    driver: bridge